gsn2x="../../../../GSN/gsn2x/target/debug/gsn2x"
index=Index-Collision.yaml

hazards:
	$(gsn2x) -o svg -a architecture.svg -f full.svg -s ../../data/case_style.css -t $(index) claim-H2.yaml claim-H1.yaml claim-UCA6.yaml claim-UCA7.yaml claim-UCA4.yaml claim-UCA1.yaml claim-TS-10.yaml claim-TS-7.yaml claim-TS-9.yaml claim-TS-8.yaml claim-TS-6.yaml claim-TS-3.yaml claim-TS-2.yaml claim-TS-5.yaml claim-TS-1.yaml claim-TS-4.yaml

clean:
	 rm *.svg
